language: c
services: docker
cache:
  directories:
  - cache

env:
  global:
    - USER=yhnw
    - REPO=openwrt-buildroot
  matrix:
    - BRANCH=15.05.1 BOARD=ar71xx VARIANT=fpuemu

script:
  - >-
    docker run
    -u openwrt
    -w /home/openwrt
    -v $(pwd):/hostdir
    -e TRAVIS=${TRAVIS}
    -e TERM=xterm
    -e COLOR=always
    ${USER}/${REPO}:${BRANCH}-${BOARD} /hostdir/build.sh ${BRANCH} ${BOARD} ${VARIANT}

after_script:
  - ls -la bin

deploy:
  - provider: releases
    api_key:
      secure: "sC76dFlU7buHevSXsLtzwUP758FsCepJNhPRwuVqukg2EzW/vOQrjJY6xJVykNYa7MV9SVOtwzenNkvff/18b1xGuGcSkDVSPdWOT52MP+bXvPc0Gu0f/GuVPHCQ7ZXpnD+MI+3JuLRfhpCNC/Pst784XkN997PwelOtsBXFyMSGCjIWLX01tWoi5Hc43rUyFml2a0uGLwCuG7wUEc7n9H4JjkigrPMCwQgst6bjVriMbL4xdxRzWTpoHRQJh8MQ//raP6bO175ZAqWHgwtor9Zp9GXuRX++61LsDFf6lCKjWbK1hwdD0QxMy3c8IPDVaHqEPYW1wwoa9XiV9iItSXUVA+QjNRNu5hlf6jaNt5EZwxQhDUVXNxbwmMLpdzaADeuot6JyZSaMFia2oxfzzQf7wL4NQ+SFK+yIlS2eL5BQmmnvg3DVZ5BIbPdDHLEynKdMTXBNzXzvLI7TSbOyL7VVU57drvZz0S0RvCx5c2C5MfXBlI0j11zCcUMMhcCce/utCiUMqhIjHLi+YgHttxKE8Z/04KKt9rTrxZh86YvPFd/aIH0ojt7J8o4UVD84UEozLFZsIf6WHQL/5TY0QQJY3WkHBs01C3UsrL+YQwRZigiWpGErpu6ugwxtdydcUzXg2hBbEm1PltNAxJLSHPd0v0IaphfcavahLrFdeDs="
    file_glob: true
    file: "bin/*.bin"
    skip_cleanup: true
    on:
      tags: true
