language: c
services: docker
cache: ccache

env:
  global:
    - USER=yhnw
    - REPO=openwrt-buildroot
  matrix:
    - BRANCH=15.05.1 ARCH=ar71xx VARIANT=fpuemu

before_script:
  - |
    if [ -n "${CLEANUP_CCACHE_DIR}" ]; then
      echo "Clean up ccache dir..."
      rm -rf ${HOME}/.ccache/*
    else
      ls -la ${HOME}/.ccache/
    fi

script:
  - >-
    docker run
    -u openwrt
    -w /home/openwrt
    -v $(pwd):/work
    -v ${HOME}/.ccache:/home/openwrt/.ccache
    ${USER}/${REPO}:${BRANCH}-${ARCH} /work/build.sh ${BRANCH} ${ARCH} ${VARIANT}

after_script:
  - ls -la bin

deploy:
  - provider: releases
    api_key:
      secure: "sC76dFlU7buHevSXsLtzwUP758FsCepJNhPRwuVqukg2EzW/vOQrjJY6xJVykNYa7MV9SVOtwzenNkvff/18b1xGuGcSkDVSPdWOT52MP+bXvPc0Gu0f/GuVPHCQ7ZXpnD+MI+3JuLRfhpCNC/Pst784XkN997PwelOtsBXFyMSGCjIWLX01tWoi5Hc43rUyFml2a0uGLwCuG7wUEc7n9H4JjkigrPMCwQgst6bjVriMbL4xdxRzWTpoHRQJh8MQ//raP6bO175ZAqWHgwtor9Zp9GXuRX++61LsDFf6lCKjWbK1hwdD0QxMy3c8IPDVaHqEPYW1wwoa9XiV9iItSXUVA+QjNRNu5hlf6jaNt5EZwxQhDUVXNxbwmMLpdzaADeuot6JyZSaMFia2oxfzzQf7wL4NQ+SFK+yIlS2eL5BQmmnvg3DVZ5BIbPdDHLEynKdMTXBNzXzvLI7TSbOyL7VVU57drvZz0S0RvCx5c2C5MfXBlI0j11zCcUMMhcCce/utCiUMqhIjHLi+YgHttxKE8Z/04KKt9rTrxZh86YvPFd/aIH0ojt7J8o4UVD84UEozLFZsIf6WHQL/5TY0QQJY3WkHBs01C3UsrL+YQwRZigiWpGErpu6ugwxtdydcUzXg2hBbEm1PltNAxJLSHPd0v0IaphfcavahLrFdeDs="
    file_glob: true
    file: "bin/*.bin"
    skip_cleanup: true
    on:
      tags: true
